import "./bootstrap";
import "./user-create/validate-inputs/process-block-one";
import "./user-create/validate-inputs/process-block-two";
import "./user-create/validate-inputs/process-block-three";
import "./user-create/process-block/index";
import "./user-create/user-create";
import "./user-login/index";
import "./utils/api-via-cep";
import "./create-service/validate-inputs/index";
import "./create-service/index";
import "./delete-service/index";
import.meta.glob(["../images/**"]);
